export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LEAVE = 'LEAVE',
  HOLIDAY = 'HOLIDAY',
  PARTIAL = 'PARTIAL',
  REGULARIZED_PRESENT = 'REGULARIZED_PRESENT',
  OPEN = 'OPEN',
  INCOMPLETE = 'INCOMPLETE',
  FLAGGED = 'FLAGGED',
  REQUIRES_REVIEW = 'REQUIRES_REVIEW',
}
